/* Явні відповідності "назва області в грі → назва області в геометрії" для випадків,
   де зіставлення за назвою не спрацьовує (різні мови / транслітерація). Формат:
   { ISO: { "назва з гри": "назва в топології" } }.
   ЗГЕНЕРОВАНО tools/build-region-overrides.mjs: центр області в SVG-карті гри
   (проєкція Kavrayskiy VII, відкалібрована за парами з назвами) → довгота/широта →
   найближчий вільний полігон (глобальне жадібне зіставлення "один до одного", із перевіркою правдоподібності розміру). */
export const REGION_MATCH_OVERRIDES = {
  AF: {"Ghazni":"Ghanzi","Sari Pul":"Sar-e Pol"},
  AO: {"Cubango":"Cuando Cubango"},
  AZ: {"Babək":"Nakhchivan Autonomous Republic"},
  BA: {"Central Bosnia":"Federation of Bosnia and Herzegovina","Serbian Republic":"Republika Srpska"},
  BE: {"Namur":"Wallonne Gewest","Flemish Brabant":"Vlaams Gewest","Brussels":"Brussels Hoofdstedelijk"},
  BF: {"Sanmatenga":"Centre-Nord","Houet":"Hauts-Bassins","Gourma":"Est","Yatenga":"Nord","Boulgou":"Centre-Est","Poni":"Sud-Ouest","Komoé":"Cascades","Oubritenga":"Plateau Central","Kadiogo":"Centre","Mou Houn":"Boucle du Mouhoun","Sissili":"Centre-Ouest","Zoundwéogo":"Centre-Sud","Séno":"Sahel"},
  BW: {"Ngamiland":"North-West District"},
  BY: {"Hrodna":"Grodno","Homyel":"Gomel","Mahilyow":"Mogilev"},
  CD: {"Bas Uele":"Lower Uele","Haut Uele":"Upper Uele","Kasaï Central":"Central Kasai"},
  CH: {"Lucerne":"Luzern","Sankt Gallen":"St. Gallen"},
  CI: {"Moyen-Comoe":"Comoe","Yamoussoukro":"District Autonome De Yamoussoukro","Abidjan":"District Autonome D'Abidjan"},
  CL: {"Ñuble":"RegiÃ³n de Ãuble","Maule":"RegiÃ³n del Maule","Aisén del General Carlos Ibáñez del Campo":"RegiÃ³n de AysÃ©n del Gral.IbaÃ±ez del Campo","Atacama":"RegiÃ³n de Atacama","Bío Bío":"RegiÃ³n del BÃ­o-BÃ­o","La Araucanía":"RegiÃ³n de La AraucanÃ­a","Los Ríos":"RegiÃ³n de Los RÃ­os","Libertador General Bernardo O Higgins":"RegiÃ³n del Libertador Bernardo O'Higgins"},
  CM: {"Est":"East","Sud Ouest":"South-West","Sud":"South","Extrême Nord":"Far North"},
  CN: {"Guangdong":"Guangzhou Province","Ningxia":"Ningxia Ningxia Hui Autonomous Region"},
  CU: {"Isla de la Juventud":"Isle of Youth","Ciudad de la Habana":"Havana"},
  DZ: {"Alger":"Algiers"},
  EE: {"Tartu":"Valga maakond","Rapla":"Pärnu maakond","Ida-Viru":"Jõgeva maakond","Põlva":"Võru maakond","Hiiu":"Saare maakond","Järva":"Rapla maakond","Jõgeva":"Tartu maakond","Harju":"Harju maakond"},
  EG: {"Al Wadi at Jadid":"New Valley Governorate","Al Jizah":"Giza Governorate","Janub Sina":"South Sinai Governorate","Shamal Sina":"North Sinai Governorate","Suhaj":"Sohag Governorate","Al Minya":"Minya Governate","Al Buhayrah":"Beheira Governorate","As Suways":"Suez Governorate","Bani Suwayf":"Beni Suef Governorate","Al Iskandariyah":"Alexandria Governorate"},
  ER: {"Debubawi Keyih Bahri":"Southern Red Sea Region","Semenawi Keyih Bahri":"Northen Red Sea Region"},
  ES: {"Cataluña":"Cataluña/Catalunya"},
  ET: {"Gambela Peoples":"Gambela","South Ethiopia Regional State":"SNNPR","Harari People":"Hareri"},
  FR: {"Corsica":"Corse"},
  GB: {"Powys":"Wales","Mid Ulster":"Northern Ireland","Highland":"Scotland","North Yorkshire":"England"},
  GL: {"Qeqqata Kommunia":"Sermersooq","Kommune Kujalleq":"Kujalleq"},
  GM: {"Upper River":"Basse","Central River":"Kuntaur","West Coast":"Brikama","North Bank":"Kerewan","Lower River":"Mansakonko"},
  GR: {"Thessalia":"Thessalia-Central Greece","Central Macedonia":"Macedonia-Thrace","Western Greece":"Peloponisos-W. Greece & Ionian"},
  HR: {"Licko-Senjska":"Lika-Senj","Splitsko-Dalmatinska":"Split-Dalmatia","Istarska":"Istria","Primorsko-Goranska":"Primorje-Gorski Kotar","Vukovarsko-Srijemska":"Vukovar-Syrmia","Brodsko-Posavska":"Brod-Posavina","Koprivnicko-Križevacka":"Koprivnica-Križevci","Krapinsko-Zagorska":"Krapina-Zagorje","Šibensko-Kninska":"Šibenik-Knin","Medimurska":"Međimurje"},
  ID: {"Kalimantan Barat":"West Kalimantan","Kalimantan Tengah":"Central Kalimantan","Sumatra Selatan":"South Sumatra","Jawa Barat":"West Java","Kalimantan Timur":"East Kalimantan","Jawa Tengah":"Central Java","Nusa Tenggara Barat":"West Nusa Tenggara","Kalimantan Selatan":"South Kalimantan","Sulawesi Selatan":"South Sulawesi","Kalimantan Utara":"North Kalimantan","Sumatra Barat":"West Sumatra","Sumatra Utara":"North Sumatra","Sulawesi Barat":"West Sulawesi","Sulawesi Tengah":"Central Sulawesi","Kepulauan Bangka Belitung":"Bangka-Belitung Islands","Jawa Timur":"East Java","Sulawesi Tenggara":"Southeast Sulawesi","Papua Barat":"West Papua","Daerah Istimewa Yogyakarta":"Special Region of Yogyakarta","Daerah Khusus Ibukota":"Jakarta Special Capital Region"},
  IE: {"Limerick":"Munster","Kildare":"Leinster","Mayo":"Connacht","Donegal":"Ulster"},
  IL: {"HaDarom":"Southern District","HaZafon":"Northern District","HaMerkaz":"Central District"},
  IQ: {"At-Ta mim":"Kirkuk","Dihok":"Dohuk"},
  IS: {"Norðurland vestra":"Southern Region","Vestfirðir":"Western Region","Norðurland eystra":"Eastern Region"},
  IT: {"Veneto":"Nord-Est","Umbria":"Centro","Basilicata":"Sud","Piemonte":"Nord-Ovest"},
  KH: {"Pouthisat":"Pursat","Krâchéh":"Kratie","Krong Pailin":"Pailin"},
  KI: {"Kiribati":"Line Islands"},
  KM: {"Andjazîdja":"Grande Comore"},
  KP: {"Hamgyŏng-bukto":"North Hamgyong","Chagang-do":"Jagang","Phyŏngan-namdo":"South Pyongan","Hamgyŏng-namdo":"South Hamgyong","Phyŏngan-bukto":"North Pyongan","Hwanghae-bukto":"North Hwanghae","Hwanghae-namdo":"South Hwanghae"},
  KR: {"Jeonnam-Gwangju":"South Jeolla"},
  KZ: {"Turkistan":"South Kazakhstan Region"},
  LB: {"North":"Liban-Nord","Mount Lebanon":"Mont-Liban","South":"Liban-Sud"},
  LK: {"Mātara":"Southern Province","Anurādhapura":"North Central Province","Puttalama":"North Western Province","Mahanuvara":"Central Province","Kŏḷamba":"Western Province","Badulla":"Uva Province","Maḍakalapuva":"Eastern Province","Mannārama":"Northern Province","Kaḷutara":"Sabaragamuwa Province"},
  LT: {"Kauno":"Kaunas County","Utenos":"Utena County"},
  MA: {"Settat Casablanca":"Casablanca-Settat"},
  MG: {"Haute Matsiatra":"Matsiatra Ambony"},
  MM: {"Sagaing":"Saigang"},
  MW: {"Dowa":"Central Region","Nkhata Bay":"Northern Region","Zomba":"Southern Region"},
  MX: {"Coahuila":"Coahuila de Zaragoza","Veracruz":"Veracruz de Ignacio de la Llave"},
  MY: {"Melaka":"Malacca","Pulau Pinang":"Penang"},
  NA: {"Zambezi":"Caprivi"},
  NI: {"Atlántico Norte":"North Carribean Coast Autonomous Region","Atlántico Sur":"South Atlantic Autonomous Region"},
  NO: {"Buskerud":"Vestfold og Telemark","Akershus":"Viken","Finnmark":"Troms og Finnmark"},
  NP: {"Karnali Pradesh":"Karnali","Koshi Pradesh":"Province 1","Bagmati Pradesh":"Bagmati","Gandaki Pradesh":"Gandaki","Lumbini Pradesh":"Lumbini"},
  OM: {"Al Dhahira":"Az Zahirah","Al Batnah North":"Al Batinah"},
  PA: {"Ngöbe Buglé":"Comarca Ngäbe-Buglé","Emberá":"Comarca Emberá-Wounaan"},
  PG: {"Sandaun":"West Sepik (Sandaun) Province","North Solomons":"Autonomous Region of Bougainville"},
  PH: {"Sultan Kudarat":"Soccsksargen","Tarlac":"Central Luzon","Zamboanga del Norte":"Zamboanga Peninsula","Iloilo City":"Western Visayas","Laguna":"Calabarzon","Agusan del Norte":"Caraga","Abra":"CAR","Samar":"Eastern Visayas","Negros Oriental":"Central Visayas","Lanao del Sur":"Northern Mindanao","Camarines Sur":"Bicol Region","Zamboanga del Sur":"ARMM"},
  QA: {"Al Khawr":"Al Khor and Al Thakhira"},
  RS: {"Severno-Banatski":"North Banat District","Grad Beograd":"Belgrade","Branicevski":"Branicevo District","Južno-Banatski":"South Banat District","Borski":"Bor District","Pcinjski":"Pcinja District","Zapadno-Backi":"West Backa District","Pomoravski":"Pomoravlje District","Severno-Backi":"North Backa District","Južno-Backi":"South Backa District","Šumadijski":"Sumadija District","Toplicki":"Toplica District","Kolubarski":"Kolubara District","Nišavski":"Nisava District","Srednje-Banatski":"Central Banat District","Pirotski":"Pirot District","Sremski":"Syrmia District","Podunavski":"Podunavlje District"},
  RU: {"Sakha Yakutia":"Sakha Republic","Nizhegorod":"Nizhny Novgorod Oblast","Orel":"Oryol Oblast","Moskovsskaya":"Moscow Oblast","Moskva":"Moscow"},
  SA: {"Al Hudud ash Shamaliyah":"Northern Borders Region","Ha il":"Hayel Region","Ar Quassim":"Al-Qassim Region","Ash Sharqiyah":"Eastern Region"},
  SI: {"Savinja":"Vzhodna","Littoral Inner Carniola":"Zahodna Slovenija"},
  SK: {"Žilinský":"Region of Žilina","Košický":"Region of Košice","Nitriansky":"Region of Nitra","Trnavský":"Region of Trnava","Trenciansky":"Region of Trenčín"},
  SO: {"Shabeellaha Dhexe":"Middle Shebelle","Jubbada Hoose":"Lower Juba","Jubbada Dhexe":"Middle Juba","Shabeellaha Hoose":"Lower Shebelle"},
  SV: {"Usulután":"Departamento de Usulután","La Paz":"Departamento de La Paz","Santa Ana":"Departamento de Santa Ana","Morazán":"Departamento de Morazán","Ahuachapán":"Departamento de Ahuachapán","La Unión":"Departamento de La Unión","San Miguel":"Departamento de San Miguel","Chalatenango":"Departamento de Chalatenango","Cabañas":"Departamento de Cabañas","Sonsonate":"Departamento de Sonsonate","Cuscatlán":"Departamento de Cuscatlán","San Salvador":"Departamento de San Salvador"},
  SY: {"Homs Hims":"Homs","Rif Dimashq":"Rural Damascus","Dayr Az Zawr":"Deir-ez-Zor"},
  TL: {"Ambeno":"Oecusse"},
  TM: {"Chardzhou":"Lebap","Tashauz":"Dasoguz","Ahal":"Ahai"},
  TR: {"K  Maras":"Kahramanmaraş","Agri":"Ağrı","Çankiri":"Çankırı"},
  TZ: {"Kaskazini Pemba":"North Pemba","Kusini Pemba":"South Pemba"},
  UG: {"Kayunga":"Eastern Region","Kaabong":"Northern Region","Masindi":"Western Region"},
  UZ: {"Surkhandarya":"Surxondaryo Region","Bukhoro":"Bukhara Region"},
  VN: {"Huế":"Thừa Thiên Huế"},
  XK: {"Kosovska Mitrovica":"District of Mitrovica","Peć":"District of Peja"},
};
